# ============================================
# IQ Series — Deploy Infrastructure
# ============================================

param(
    [Parameter(Mandatory=$true)]
    [string]$ResourceGroupName,

    [Parameter(Mandatory=$true)]
    [string]$Location,

    [string]$ResourcePrefix = "iqseries",

    [string]$SearchSku = "standard"
)

Write-Host "========================================"
Write-Host "IQ Series — Infrastructure Deployment"
Write-Host "========================================"
Write-Host ""

# Check Azure CLI
try {
    $azVersion = az version --query '"azure-cli"' -o tsv
    Write-Host "✓ Azure CLI version: $azVersion"
} catch {
    Write-Host "✗ Azure CLI is not installed"
    Write-Host "  Install from: https://learn.microsoft.com/cli/azure/install-azure-cli"
    exit 1
}

# Check login
Write-Host ""
Write-Host "Checking Azure login status..."
try {
    $accountName = az account show --query name -o tsv
    $userName = az account show --query user.name -o tsv
    Write-Host "✓ Logged in as: $userName"
    Write-Host "✓ Subscription: $accountName"
} catch {
    Write-Host "✗ Not logged in to Azure. Run: az login"
    exit 1
}

# Get user object ID
Write-Host ""
Write-Host "Getting user object ID..."
$userObjectId = az ad signed-in-user show --query id -o tsv
Write-Host "✓ User Object ID: $userObjectId"

# Create resource group
Write-Host ""
Write-Host "Creating resource group: $ResourceGroupName"
$exists = az group exists --name $ResourceGroupName
if ($exists -eq "true") {
    Write-Host "✓ Resource group already exists"
} else {
    az group create --name $ResourceGroupName --location $Location --output none
    Write-Host "✓ Resource group created"
}

# Deploy Bicep template
Write-Host ""
Write-Host "Deploying infrastructure (this may take 5-10 minutes)..."
Write-Host "  Resource Prefix: $ResourcePrefix"
Write-Host "  Location: $Location"
Write-Host "  Search SKU: $SearchSku"
Write-Host ""

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$bicepFile = Join-Path $scriptDir "main.bicep"

$deploymentOutput = az deployment group create `
    --resource-group $ResourceGroupName `
    --template-file $bicepFile `
    --parameters userObjectId=$userObjectId `
    --parameters resourcePrefix=$ResourcePrefix `
    --parameters location=$Location `
    --parameters searchServiceSku=$SearchSku `
    --output json | ConvertFrom-Json

Write-Host "✓ Infrastructure deployed successfully!"

# Extract outputs
$searchEndpoint = $deploymentOutput.properties.outputs.searchEndpoint.value
$aoaiEndpoint = $deploymentOutput.properties.outputs.openAiEndpoint.value
$aiServicesEndpoint = $deploymentOutput.properties.outputs.aiServicesEndpoint.value
$embeddingDeployment = $deploymentOutput.properties.outputs.embeddingDeploymentName.value
$chatDeployment = $deploymentOutput.properties.outputs.chatDeploymentName.value
$foundryProjectEndpoint = $deploymentOutput.properties.outputs.foundryProjectEndpoint.value
$searchConnectionName = $deploymentOutput.properties.outputs.searchConnectionName.value

# Create .env file
$envFile = Join-Path $scriptDir "../.env"
$envContent = @"
# IQ Series — Generated by deploy.ps1
# Resource Group: $ResourceGroupName

SEARCH_ENDPOINT=$searchEndpoint
AOAI_ENDPOINT=$aoaiEndpoint
AOAI_EMBEDDING_MODEL=text-embedding-3-large
AOAI_EMBEDDING_DEPLOYMENT=$embeddingDeployment
AOAI_GPT_MODEL=gpt-4o-mini
AOAI_GPT_DEPLOYMENT=$chatDeployment
FOUNDRY_PROJECT_ENDPOINT=$foundryProjectEndpoint
FOUNDRY_MODEL_DEPLOYMENT_NAME=gpt-4o-mini
AZURE_AI_SEARCH_CONNECTION_NAME=$searchConnectionName
"@

Set-Content -Path $envFile -Value $envContent
Write-Host ""
Write-Host "✓ .env file created at: $envFile"

# Display summary
Write-Host ""
Write-Host "========================================"
Write-Host "Deployment Complete!"
Write-Host "========================================"
Write-Host ""
Write-Host "Resources deployed:"
Write-Host "  AI Search:        $searchEndpoint"
Write-Host "  Azure OpenAI:     $aoaiEndpoint"
Write-Host "  AI Services:      $aiServicesEndpoint"
Write-Host "  Foundry Project:  $foundryProjectEndpoint"
Write-Host ""
Write-Host "Models deployed:"
Write-Host "  Embedding:   $embeddingDeployment"
Write-Host "  Chat:        $chatDeployment"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Copy the .env file to your cookbook folder and run the notebooks!"
Write-Host "     Copy-Item .env 1-Foundry-IQ-Unlocking-Knowledge-for-Agents/cookbook/.env"
Write-Host "     cd 1-Foundry-IQ-Unlocking-Knowledge-for-Agents/cookbook/"
Write-Host ""
Write-Host "Cleanup:"
Write-Host "  az group delete --name $ResourceGroupName --yes --no-wait"
Write-Host ""
