#!/bin/bash
set -e

# ============================================
# IQ Series — Deploy Infrastructure
# ============================================

RESOURCE_GROUP=""
LOCATION=""
RESOURCE_PREFIX="iqseries"
SEARCH_SKU="standard"

# Parse arguments
while getopts "g:l:p:s:h" opt; do
  case $opt in
    g) RESOURCE_GROUP="$OPTARG" ;;
    l) LOCATION="$OPTARG" ;;
    p) RESOURCE_PREFIX="$OPTARG" ;;
    s) SEARCH_SKU="$OPTARG" ;;
    h)
      echo "Usage: $0 -g <resource-group> -l <location> [-p <prefix>] [-s <search-sku>]"
      echo ""
      echo "Required:"
      echo "  -g  Resource group name"
      echo "  -l  Azure location (e.g., eastus2)"
      echo ""
      echo "Optional:"
      echo "  -p  Resource prefix (default: iqseries)"
      echo "  -s  Search service SKU (default: standard)"
      echo "  -h  Show this help message"
      exit 0
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

# Validate required params
if [ -z "$RESOURCE_GROUP" ] || [ -z "$LOCATION" ]; then
  echo "Error: Resource group (-g) and location (-l) are required"
  echo "Use -h for help"
  exit 1
fi

echo "========================================"
echo "IQ Series — Infrastructure Deployment"
echo "========================================"
echo ""

# Check Azure CLI
if ! command -v az &> /dev/null; then
  echo "✗ Azure CLI is not installed"
  echo "  Install from: https://learn.microsoft.com/cli/azure/install-azure-cli"
  exit 1
fi

AZ_VERSION=$(az version --query '"azure-cli"' -o tsv)
echo "✓ Azure CLI version: $AZ_VERSION"

# Check login
echo ""
echo "Checking Azure login status..."
if ! az account show &> /dev/null; then
  echo "✗ Not logged in to Azure. Run: az login"
  exit 1
fi

ACCOUNT_NAME=$(az account show --query name -o tsv)
USER_NAME=$(az account show --query user.name -o tsv)
echo "✓ Logged in as: $USER_NAME"
echo "✓ Subscription: $ACCOUNT_NAME"

# Get user object ID
echo ""
echo "Getting user object ID..."
USER_OBJECT_ID=$(az ad signed-in-user show --query id -o tsv)
echo "✓ User Object ID: $USER_OBJECT_ID"

# Create resource group
echo ""
echo "Creating resource group: $RESOURCE_GROUP"
if az group exists --name "$RESOURCE_GROUP" | grep -q "true"; then
  echo "✓ Resource group already exists"
else
  az group create --name "$RESOURCE_GROUP" --location "$LOCATION" --output none
  echo "✓ Resource group created"
fi

# Deploy Bicep template
echo ""
echo "Deploying infrastructure (this may take 5-10 minutes)..."
echo "  Resource Prefix: $RESOURCE_PREFIX"
echo "  Location: $LOCATION"
echo "  Search SKU: $SEARCH_SKU"
echo ""

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BICEP_FILE="$SCRIPT_DIR/main.bicep"

DEPLOYMENT_OUTPUT=$(az deployment group create \
  --resource-group "$RESOURCE_GROUP" \
  --template-file "$BICEP_FILE" \
  --parameters userObjectId="$USER_OBJECT_ID" \
  --parameters resourcePrefix="$RESOURCE_PREFIX" \
  --parameters location="$LOCATION" \
  --parameters searchServiceSku="$SEARCH_SKU" \
  --output json)

echo "✓ Infrastructure deployed successfully!"

# Extract outputs
SEARCH_ENDPOINT=$(echo "$DEPLOYMENT_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['properties']['outputs']['searchEndpoint']['value'])")
AOAI_ENDPOINT=$(echo "$DEPLOYMENT_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['properties']['outputs']['openAiEndpoint']['value'])")
AI_SERVICES_ENDPOINT=$(echo "$DEPLOYMENT_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['properties']['outputs']['aiServicesEndpoint']['value'])")
AI_SERVICES_NAME=$(echo "$DEPLOYMENT_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['properties']['outputs']['aiServicesName']['value'])")
EMBEDDING_DEPLOYMENT=$(echo "$DEPLOYMENT_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['properties']['outputs']['embeddingDeploymentName']['value'])")
CHAT_DEPLOYMENT=$(echo "$DEPLOYMENT_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['properties']['outputs']['chatDeploymentName']['value'])")
FOUNDRY_PROJECT_ENDPOINT=$(echo "$DEPLOYMENT_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['properties']['outputs']['foundryProjectEndpoint']['value'])")
SEARCH_CONNECTION_NAME=$(echo "$DEPLOYMENT_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['properties']['outputs']['searchConnectionName']['value'])")

# Create .env file
ENV_FILE="$SCRIPT_DIR/../.env"
cat > "$ENV_FILE" << EOF
# IQ Series — Generated by deploy.sh
# Resource Group: $RESOURCE_GROUP

SEARCH_ENDPOINT=$SEARCH_ENDPOINT
AOAI_ENDPOINT=$AOAI_ENDPOINT
AOAI_EMBEDDING_MODEL=text-embedding-3-large
AOAI_EMBEDDING_DEPLOYMENT=$EMBEDDING_DEPLOYMENT
AOAI_GPT_MODEL=gpt-4o-mini
AOAI_GPT_DEPLOYMENT=$CHAT_DEPLOYMENT
FOUNDRY_PROJECT_ENDPOINT=$FOUNDRY_PROJECT_ENDPOINT
FOUNDRY_MODEL_DEPLOYMENT_NAME=gpt-4o-mini
AZURE_AI_SEARCH_CONNECTION_NAME=$SEARCH_CONNECTION_NAME
EOF

echo ""
echo "✓ .env file created at: $ENV_FILE"

# Display summary
echo ""
echo "========================================"
echo "Deployment Complete!"
echo "========================================"
echo ""
echo "Resources deployed:"
echo "  AI Search:        $SEARCH_ENDPOINT"
echo "  Azure OpenAI:     $AOAI_ENDPOINT"
echo "  AI Services:      $AI_SERVICES_ENDPOINT"
echo "  Foundry Project:  $FOUNDRY_PROJECT_ENDPOINT"
echo ""
echo "Models deployed:"
echo "  Embedding:   $EMBEDDING_DEPLOYMENT"
echo "  Chat:        $CHAT_DEPLOYMENT"
echo ""
echo "Next steps:"
echo "  1. Copy the .env file to your cookbook folder and run the notebooks!"
echo "     cp .env 1-Foundry-IQ-Unlocking-Knowledge-for-Agents/cookbook/.env"
echo "     cd 1-Foundry-IQ-Unlocking-Knowledge-for-Agents/cookbook/"
echo ""
echo "Cleanup:"
echo "  az group delete --name $RESOURCE_GROUP --yes --no-wait"
echo ""
